package ua.org.shaddy.tools.url;

class CurlOptions {
	public static var AUTOREFERER:Int;
	public static var BINARYTRANSFER:Int;
	public static var BUFFERSIZE:Int;
	public static var CAINFO:Int;
	public static var CAPATH:Int;
	public static var CLOSEPOLICY:Int;
	public static var CONNECTTIMEOUT:Int;
	public static var COOKIE:Int;
	public static var COOKIEFILE:Int;
	public static var COOKIEJAR:Int;
	public static var COOKIESESSION:Int;
	public static var CRLF:Int;
	public static var CUSTOMREQUEST:Int;
	public static var DNS_CACHE_TIMEOUT:Int;
	public static var DNS_USE_GLOBAL_CACHE:Int;
	public static var EGDSOCKET:Int;
	public static var ENCODING:Int;
	public static var FAILONERROR:Int;
	public static var FILE:Int;
	public static var FILETIME:Int;
	public static var FOLLOWLOCATION:Int;
	public static var FORBID_REUSE:Int;
	public static var FRESH_CONNECT:Int;
	public static var FTPAPPEND:Int;
	public static var FTPLISTONLY:Int;
	public static var FTPPORT:Int;
	public static var FTP_USE_EPRT:Int;
	public static var FTP_USE_EPSV:Int;
	public static var HEADER:Int;
	public static var HEADERFUNCTION:Int;
	public static var HTTP200ALIASES:Int;
	public static var HTTPGET:Int;
	public static var HTTPHEADER:Int;
	public static var HTTPPROXYTUNNEL:Int;
	public static var HTTP_VERSION:Int;
	public static var INFILE:Int;
	public static var INFILESIZE:Int;
	public static var INTERFACE:Int;
	public static var KRB4LEVEL:Int;
	public static var LOW_SPEED_LIMIT:Int;
	public static var LOW_SPEED_TIME:Int;
	public static var MAXCONNECTS:Int;
	public static var MAXREDIRS:Int;
	public static var NETRC:Int;
	public static var NOBODY:Int;
	public static var NOPROGRESS:Int;
	public static var NOSIGNAL:Int;
	public static var PORT:Int;
	public static var POST:Int;
	public static var POSTFIELDS:Int;
	public static var POSTQUOTE:Int;
	public static var PREQUOTE:Int;
	public static var PRIVATE:Int;
	public static var PROGRESSFUNCTION:Int;
	public static var PROXY:Int;
	public static var PROXYPORT:Int;
	public static var PROXYTYPE:Int;
	public static var PROXYUSERPWD:Int;
	public static var PUT:Int;
	public static var QUOTE:Int;
	public static var RANDOM_FILE:Int;
	public static var RANGE:Int;
	public static var READDATA:Int;
	public static var READFUNCTION:Int;
	public static var REFERER:Int;
	public static var RESUME_FROM:Int;
	public static var RETURNTRANSFER:Int;
	public static var SHARE:Int;
	public static var SSLCERT:Int;
	public static var SSLCERTPASSWD:Int;
	public static var SSLCERTTYPE:Int;
	public static var SSLENGINE:Int;
	public static var SSLENGINE_DEFAULT:Int;
	public static var SSLKEY:Int;
	public static var SSLKEYPASSWD:Int;
	public static var SSLKEYTYPE:Int;
	public static var SSLVERSION:Int;
	public static var SSL_CIPHER_LIST:Int;
	public static var SSL_VERIFYHOST:Int;
	public static var SSL_VERIFYPEER:Int;
	public static var STDERR:Int;
	public static var TELNETOPTIONS:Int;
	public static var TIMECONDITION:Int;
	public static var TIMEOUT:Int;
	public static var TIMEVALUE:Int;
	public static var TRANSFERTEXT:Int;
	public static var UNRESTRICTED_AUTH:Int;
	public static var UPLOAD:Int;
	public static var URL:Int;
	public static var USERAGENT:Int;
	public static var USERPWD:Int;
	public static var VERBOSE:Int;
	public static var WRITEFUNCTION:Int;
	public static var WRITEHEADER:Int;
	public static var HTTPAUTH:Int;
	public static var FTP_CREATE_MISSING_DIRS:Int;
	public static var PROXYAUTH:Int;
	public static var FTP_RESPONSE_TIMEOUT:Int;
	public static var IPRESOLVE:Int;
	public static var MAXFILESIZE:Int;
	public static var FTP_SSL:Int;
	public static var NETRC_FILE:Int;
	public static var FTPSSLAUTH:Int;
	public static var FTP_ACCOUNT:Int;
	public static var TCP_NODELAY:Int;
	public static var COOKIELIST:Int;
	public static var IGNORE_CONTENT_LENGTH:Int;
	public static var FTP_SKIP_PASV_IP:Int;
	public static var FTP_FILEMETHOD:Int;
	public static var CONNECT_ONLY:Int;
	public static var LOCALPORT:Int;
	public static var LOCALPORTRANGE:Int;
	public static var FTP_ALTERNATIVE_TO_USER:Int;
	public static var MAX_RECV_SPEED_LARGE:Int;
	public static var MAX_SEND_SPEED_LARGE:Int;
	public static var SSL_SESSIONID_CACHE:Int;
	public static var FTP_SSL_CCC:Int;
	public static var SSH_AUTH_TYPES:Int;
	public static var SSH_PRIVATE_KEYFILE:Int;
	public static var SSH_PUBLIC_KEYFILE:Int;
	public static var CONNECTTIMEOUT_MS:Int;
	public static var HTTP_CONTENT_DECODING:Int;
	public static var HTTP_TRANSFER_DECODING:Int;
	public static var TIMEOUT_MS:Int;
	public static var KRBLEVEL:Int;
	public static var NEW_DIRECTORY_PERMS:Int;
	public static var NEW_FILE_PERMS:Int;
	public static var APPEND:Int;
	public static var DIRLISTONLY:Int;
	public static var USE_SSL:Int;
	public static var SSH_HOST_PUBLIC_KEY_MD5:Int;
	public static var PROXY_TRANSFER_MODE:Int;
	public static var ADDRESS_SCOPE:Int;
	public static var CRLFILE:Int;
	public static var ISSUERCERT:Int;
	public static var KEYPASSWD:Int;
	public static var CERTINFO:Int;
	public static var PASSWORD:Int;
	public static var POSTREDIR:Int;
	public static var PROXYPASSWORD:Int;
	public static var PROXYUSERNAME:Int;
	public static var USERNAME:Int;
	public static var NOPROXY:Int;
	public static var PROTOCOLS:Int;
	public static var REDIR_PROTOCOLS:Int;
	public static var SOCKS5_GSSAPI_NEC:Int;
	public static var SOCKS5_GSSAPI_SERVICE:Int;
	public static var TFTP_BLKSIZE:Int;
	public static var SSH_KNOWNHOSTS:Int;
	public static var FTP_USE_PRET:Int;
	public static var MAIL_FROM:Int;
	public static var MAIL_RCPT:Int;
	public static var RTSP_CLIENT_CSEQ:Int;
	public static var RTSP_REQUEST:Int;
	public static var RTSP_SERVER_CSEQ:Int;
	public static var RTSP_SESSION_ID:Int;
	public static var RTSP_STREAM_URI:Int;
	public static var RTSP_TRANSPORT:Int;
	public static var FNMATCH_FUNCTION:Int;
	public static var WILDCARDMATCH:Int;
	public static var RESOLVE:Int;
	public static var TLSAUTH_PASSWORD:Int;
	public static var TLSAUTH_TYPE:Int;
	public static var TLSAUTH_USERNAME:Int;
	public static var ACCEPT_ENCODING:Int;
	public static var TRANSFER_ENCODING:Int;
	public static var GSSAPI_DELEGATION:Int;
	public static var ACCEPTTIMEOUT_MS:Int;
	public static var DNS_SERVERS:Int;
	public static var MAIL_AUTH:Int;
	public static var SSL_OPTIONS:Int;
	public static var TCP_KEEPALIVE:Int;
	public static var TCP_KEEPIDLE:Int;
	public static var TCP_KEEPINTVL:Int;
	public static var SAFE_UPLOAD:Int;
	static function __init__(){
		AUTOREFERER = untyped __php__ ("CURLOPT_AUTOREFERER");
		BINARYTRANSFER = untyped __php__ ("CURLOPT_BINARYTRANSFER");
		BUFFERSIZE = untyped __php__ ("CURLOPT_BUFFERSIZE");
		CAINFO = untyped __php__ ("CURLOPT_CAINFO");
		CAPATH = untyped __php__ ("CURLOPT_CAPATH");
		CLOSEPOLICY = untyped __php__ ("CURLOPT_CLOSEPOLICY");
		CONNECTTIMEOUT = untyped __php__ ("CURLOPT_CONNECTTIMEOUT");
		COOKIE = untyped __php__ ("CURLOPT_COOKIE");
		COOKIEFILE = untyped __php__ ("CURLOPT_COOKIEFILE");
		COOKIEJAR = untyped __php__ ("CURLOPT_COOKIEJAR");
		COOKIESESSION = untyped __php__ ("CURLOPT_COOKIESESSION");
		CRLF = untyped __php__ ("CURLOPT_CRLF");
		CUSTOMREQUEST = untyped __php__ ("CURLOPT_CUSTOMREQUEST");
		DNS_CACHE_TIMEOUT = untyped __php__ ("CURLOPT_DNS_CACHE_TIMEOUT");
		DNS_USE_GLOBAL_CACHE = untyped __php__ ("CURLOPT_DNS_USE_GLOBAL_CACHE");
		EGDSOCKET = untyped __php__ ("CURLOPT_EGDSOCKET");
		ENCODING = untyped __php__ ("CURLOPT_ENCODING");
		FAILONERROR = untyped __php__ ("CURLOPT_FAILONERROR");
		FILE = untyped __php__ ("CURLOPT_FILE");
		FILETIME = untyped __php__ ("CURLOPT_FILETIME");
		FOLLOWLOCATION = untyped __php__ ("CURLOPT_FOLLOWLOCATION");
		FORBID_REUSE = untyped __php__ ("CURLOPT_FORBID_REUSE");
		FRESH_CONNECT = untyped __php__ ("CURLOPT_FRESH_CONNECT");
		FTPAPPEND = untyped __php__ ("CURLOPT_FTPAPPEND");
		FTPLISTONLY = untyped __php__ ("CURLOPT_FTPLISTONLY");
		FTPPORT = untyped __php__ ("CURLOPT_FTPPORT");
		FTP_USE_EPRT = untyped __php__ ("CURLOPT_FTP_USE_EPRT");
		FTP_USE_EPSV = untyped __php__ ("CURLOPT_FTP_USE_EPSV");
		HEADER = untyped __php__ ("CURLOPT_HEADER");
		HEADERFUNCTION = untyped __php__ ("CURLOPT_HEADERFUNCTION");
		HTTP200ALIASES = untyped __php__ ("CURLOPT_HTTP200ALIASES");
		HTTPGET = untyped __php__ ("CURLOPT_HTTPGET");
		HTTPHEADER = untyped __php__ ("CURLOPT_HTTPHEADER");
		HTTPPROXYTUNNEL = untyped __php__ ("CURLOPT_HTTPPROXYTUNNEL");
		HTTP_VERSION = untyped __php__ ("CURLOPT_HTTP_VERSION");
		INFILE = untyped __php__ ("CURLOPT_INFILE");
		INFILESIZE = untyped __php__ ("CURLOPT_INFILESIZE");
		INTERFACE = untyped __php__ ("CURLOPT_INTERFACE");
		KRB4LEVEL = untyped __php__ ("CURLOPT_KRB4LEVEL");
		LOW_SPEED_LIMIT = untyped __php__ ("CURLOPT_LOW_SPEED_LIMIT");
		LOW_SPEED_TIME = untyped __php__ ("CURLOPT_LOW_SPEED_TIME");
		MAXCONNECTS = untyped __php__ ("CURLOPT_MAXCONNECTS");
		MAXREDIRS = untyped __php__ ("CURLOPT_MAXREDIRS");
		NETRC = untyped __php__ ("CURLOPT_NETRC");
		NOBODY = untyped __php__ ("CURLOPT_NOBODY");
		NOPROGRESS = untyped __php__ ("CURLOPT_NOPROGRESS");
		NOSIGNAL = untyped __php__ ("CURLOPT_NOSIGNAL");
		PORT = untyped __php__ ("CURLOPT_PORT");
		POST = untyped __php__ ("CURLOPT_POST");
		POSTFIELDS = untyped __php__ ("CURLOPT_POSTFIELDS");
		POSTQUOTE = untyped __php__ ("CURLOPT_POSTQUOTE");
		PREQUOTE = untyped __php__ ("CURLOPT_PREQUOTE");
		PRIVATE = untyped __php__ ("CURLOPT_PRIVATE");
		PROGRESSFUNCTION = untyped __php__ ("CURLOPT_PROGRESSFUNCTION");
		PROXY = untyped __php__ ("CURLOPT_PROXY");
		PROXYPORT = untyped __php__ ("CURLOPT_PROXYPORT");
		PROXYTYPE = untyped __php__ ("CURLOPT_PROXYTYPE");
		PROXYUSERPWD = untyped __php__ ("CURLOPT_PROXYUSERPWD");
		PUT = untyped __php__ ("CURLOPT_PUT");
		QUOTE = untyped __php__ ("CURLOPT_QUOTE");
		RANDOM_FILE = untyped __php__ ("CURLOPT_RANDOM_FILE");
		RANGE = untyped __php__ ("CURLOPT_RANGE");
		READDATA = untyped __php__ ("CURLOPT_READDATA");
		READFUNCTION = untyped __php__ ("CURLOPT_READFUNCTION");
		REFERER = untyped __php__ ("CURLOPT_REFERER");
		RESUME_FROM = untyped __php__ ("CURLOPT_RESUME_FROM");
		RETURNTRANSFER = untyped __php__ ("CURLOPT_RETURNTRANSFER");
		SHARE = untyped __php__ ("CURLOPT_SHARE");
		SSLCERT = untyped __php__ ("CURLOPT_SSLCERT");
		SSLCERTPASSWD = untyped __php__ ("CURLOPT_SSLCERTPASSWD");
		SSLCERTTYPE = untyped __php__ ("CURLOPT_SSLCERTTYPE");
		SSLENGINE = untyped __php__ ("CURLOPT_SSLENGINE");
		SSLENGINE_DEFAULT = untyped __php__ ("CURLOPT_SSLENGINE_DEFAULT");
		SSLKEY = untyped __php__ ("CURLOPT_SSLKEY");
		SSLKEYPASSWD = untyped __php__ ("CURLOPT_SSLKEYPASSWD");
		SSLKEYTYPE = untyped __php__ ("CURLOPT_SSLKEYTYPE");
		SSLVERSION = untyped __php__ ("CURLOPT_SSLVERSION");
		SSL_CIPHER_LIST = untyped __php__ ("CURLOPT_SSL_CIPHER_LIST");
		SSL_VERIFYHOST = untyped __php__ ("CURLOPT_SSL_VERIFYHOST");
		SSL_VERIFYPEER = untyped __php__ ("CURLOPT_SSL_VERIFYPEER");
		STDERR = untyped __php__ ("CURLOPT_STDERR");
		TELNETOPTIONS = untyped __php__ ("CURLOPT_TELNETOPTIONS");
		TIMECONDITION = untyped __php__ ("CURLOPT_TIMECONDITION");
		TIMEOUT = untyped __php__ ("CURLOPT_TIMEOUT");
		TIMEVALUE = untyped __php__ ("CURLOPT_TIMEVALUE");
		TRANSFERTEXT = untyped __php__ ("CURLOPT_TRANSFERTEXT");
		UNRESTRICTED_AUTH = untyped __php__ ("CURLOPT_UNRESTRICTED_AUTH");
		UPLOAD = untyped __php__ ("CURLOPT_UPLOAD");
		URL = untyped __php__ ("CURLOPT_URL");
		USERAGENT = untyped __php__ ("CURLOPT_USERAGENT");
		USERPWD = untyped __php__ ("CURLOPT_USERPWD");
		VERBOSE = untyped __php__ ("CURLOPT_VERBOSE");
		WRITEFUNCTION = untyped __php__ ("CURLOPT_WRITEFUNCTION");
		WRITEHEADER = untyped __php__ ("CURLOPT_WRITEHEADER");
		HTTPAUTH = untyped __php__ ("CURLOPT_HTTPAUTH");
		FTP_CREATE_MISSING_DIRS = untyped __php__ ("CURLOPT_FTP_CREATE_MISSING_DIRS");
		PROXYAUTH = untyped __php__ ("CURLOPT_PROXYAUTH");
		FTP_RESPONSE_TIMEOUT = untyped __php__ ("CURLOPT_FTP_RESPONSE_TIMEOUT");
		IPRESOLVE = untyped __php__ ("CURLOPT_IPRESOLVE");
		MAXFILESIZE = untyped __php__ ("CURLOPT_MAXFILESIZE");
		FTP_SSL = untyped __php__ ("CURLOPT_FTP_SSL");
		NETRC_FILE = untyped __php__ ("CURLOPT_NETRC_FILE");
		FTPSSLAUTH = untyped __php__ ("CURLOPT_FTPSSLAUTH");
		FTP_ACCOUNT = untyped __php__ ("CURLOPT_FTP_ACCOUNT");
		TCP_NODELAY = untyped __php__ ("CURLOPT_TCP_NODELAY");
		COOKIELIST = untyped __php__ ("CURLOPT_COOKIELIST");
		IGNORE_CONTENT_LENGTH = untyped __php__ ("CURLOPT_IGNORE_CONTENT_LENGTH");
		FTP_SKIP_PASV_IP = untyped __php__ ("CURLOPT_FTP_SKIP_PASV_IP");
		FTP_FILEMETHOD = untyped __php__ ("CURLOPT_FTP_FILEMETHOD");
		CONNECT_ONLY = untyped __php__ ("CURLOPT_CONNECT_ONLY");
		LOCALPORT = untyped __php__ ("CURLOPT_LOCALPORT");
		LOCALPORTRANGE = untyped __php__ ("CURLOPT_LOCALPORTRANGE");
		FTP_ALTERNATIVE_TO_USER = untyped __php__ ("CURLOPT_FTP_ALTERNATIVE_TO_USER");
		MAX_RECV_SPEED_LARGE = untyped __php__ ("CURLOPT_MAX_RECV_SPEED_LARGE");
		MAX_SEND_SPEED_LARGE = untyped __php__ ("CURLOPT_MAX_SEND_SPEED_LARGE");
		SSL_SESSIONID_CACHE = untyped __php__ ("CURLOPT_SSL_SESSIONID_CACHE");
		FTP_SSL_CCC = untyped __php__ ("CURLOPT_FTP_SSL_CCC");
		SSH_AUTH_TYPES = untyped __php__ ("CURLOPT_SSH_AUTH_TYPES");
		SSH_PRIVATE_KEYFILE = untyped __php__ ("CURLOPT_SSH_PRIVATE_KEYFILE");
		SSH_PUBLIC_KEYFILE = untyped __php__ ("CURLOPT_SSH_PUBLIC_KEYFILE");
		CONNECTTIMEOUT_MS = untyped __php__ ("CURLOPT_CONNECTTIMEOUT_MS");
		HTTP_CONTENT_DECODING = untyped __php__ ("CURLOPT_HTTP_CONTENT_DECODING");
		HTTP_TRANSFER_DECODING = untyped __php__ ("CURLOPT_HTTP_TRANSFER_DECODING");
		TIMEOUT_MS = untyped __php__ ("CURLOPT_TIMEOUT_MS");
		KRBLEVEL = untyped __php__ ("CURLOPT_KRBLEVEL");
		NEW_DIRECTORY_PERMS = untyped __php__ ("CURLOPT_NEW_DIRECTORY_PERMS");
		NEW_FILE_PERMS = untyped __php__ ("CURLOPT_NEW_FILE_PERMS");
		APPEND = untyped __php__ ("CURLOPT_APPEND");
		DIRLISTONLY = untyped __php__ ("CURLOPT_DIRLISTONLY");
		USE_SSL = untyped __php__ ("CURLOPT_USE_SSL");
		SSH_HOST_PUBLIC_KEY_MD5 = untyped __php__ ("CURLOPT_SSH_HOST_PUBLIC_KEY_MD5");
		PROXY_TRANSFER_MODE = untyped __php__ ("CURLOPT_PROXY_TRANSFER_MODE");
		ADDRESS_SCOPE = untyped __php__ ("CURLOPT_ADDRESS_SCOPE");
		CRLFILE = untyped __php__ ("CURLOPT_CRLFILE");
		ISSUERCERT = untyped __php__ ("CURLOPT_ISSUERCERT");
		KEYPASSWD = untyped __php__ ("CURLOPT_KEYPASSWD");
		CERTINFO = untyped __php__ ("CURLOPT_CERTINFO");
		PASSWORD = untyped __php__ ("CURLOPT_PASSWORD");
		POSTREDIR = untyped __php__ ("CURLOPT_POSTREDIR");
		PROXYPASSWORD = untyped __php__ ("CURLOPT_PROXYPASSWORD");
		PROXYUSERNAME = untyped __php__ ("CURLOPT_PROXYUSERNAME");
		USERNAME = untyped __php__ ("CURLOPT_USERNAME");
		NOPROXY = untyped __php__ ("CURLOPT_NOPROXY");
		PROTOCOLS = untyped __php__ ("CURLOPT_PROTOCOLS");
		REDIR_PROTOCOLS = untyped __php__ ("CURLOPT_REDIR_PROTOCOLS");
		SOCKS5_GSSAPI_NEC = untyped __php__ ("CURLOPT_SOCKS5_GSSAPI_NEC");
		SOCKS5_GSSAPI_SERVICE = untyped __php__ ("CURLOPT_SOCKS5_GSSAPI_SERVICE");
		TFTP_BLKSIZE = untyped __php__ ("CURLOPT_TFTP_BLKSIZE");
		SSH_KNOWNHOSTS = untyped __php__ ("CURLOPT_SSH_KNOWNHOSTS");
		FTP_USE_PRET = untyped __php__ ("CURLOPT_FTP_USE_PRET");
		MAIL_FROM = untyped __php__ ("CURLOPT_MAIL_FROM");
		MAIL_RCPT = untyped __php__ ("CURLOPT_MAIL_RCPT");
		RTSP_CLIENT_CSEQ = untyped __php__ ("CURLOPT_RTSP_CLIENT_CSEQ");
		RTSP_REQUEST = untyped __php__ ("CURLOPT_RTSP_REQUEST");
		RTSP_SERVER_CSEQ = untyped __php__ ("CURLOPT_RTSP_SERVER_CSEQ");
		RTSP_SESSION_ID = untyped __php__ ("CURLOPT_RTSP_SESSION_ID");
		RTSP_STREAM_URI = untyped __php__ ("CURLOPT_RTSP_STREAM_URI");
		RTSP_TRANSPORT = untyped __php__ ("CURLOPT_RTSP_TRANSPORT");
		FNMATCH_FUNCTION = untyped __php__ ("CURLOPT_FNMATCH_FUNCTION");
		WILDCARDMATCH = untyped __php__ ("CURLOPT_WILDCARDMATCH");
		RESOLVE = untyped __php__ ("CURLOPT_RESOLVE");
		TLSAUTH_PASSWORD = untyped __php__ ("CURLOPT_TLSAUTH_PASSWORD");
		TLSAUTH_TYPE = untyped __php__ ("CURLOPT_TLSAUTH_TYPE");
		TLSAUTH_USERNAME = untyped __php__ ("CURLOPT_TLSAUTH_USERNAME");
		ACCEPT_ENCODING = untyped __php__ ("CURLOPT_ACCEPT_ENCODING");
		TRANSFER_ENCODING = untyped __php__ ("CURLOPT_TRANSFER_ENCODING");
		GSSAPI_DELEGATION = untyped __php__ ("CURLOPT_GSSAPI_DELEGATION");
		ACCEPTTIMEOUT_MS = untyped __php__ ("CURLOPT_ACCEPTTIMEOUT_MS");
		DNS_SERVERS = untyped __php__ ("CURLOPT_DNS_SERVERS");
		MAIL_AUTH = untyped __php__ ("CURLOPT_MAIL_AUTH");
		SSL_OPTIONS = untyped __php__ ("CURLOPT_SSL_OPTIONS");
		TCP_KEEPALIVE = untyped __php__ ("CURLOPT_TCP_KEEPALIVE");
		TCP_KEEPIDLE = untyped __php__ ("CURLOPT_TCP_KEEPIDLE");
		TCP_KEEPINTVL = untyped __php__ ("CURLOPT_TCP_KEEPINTVL");
		SAFE_UPLOAD = untyped __php__ ("CURLOPT_SAFE_UPLOAD");
	}
}