package ua.org.shaddy.tools.url;

@:headerCode("#include <curl/curl.h>")

class CurlInfo {
	public static var CONNECT_TIME:Int;
	public static var CONTENT_LENGTH_DOWNLOAD:Int;
	public static var CONTENT_LENGTH_UPLOAD:Int;
	public static var CONTENT_TYPE:Int;
	public static var EFFECTIVE_URL:Int;
	public static var FILETIME:Int;
	public static var HEADER_OUT:Int;
	public static var HEADER_SIZE:Int;
	public static var HTTP_CODE:Int;
	public static var LASTONE:Int;
	public static var NAMELOOKUP_TIME:Int;
	public static var PRETRANSFER_TIME:Int;
	public static var PRIVATE:Int;
	public static var REDIRECT_COUNT:Int;
	public static var REDIRECT_TIME:Int;
	public static var REQUEST_SIZE:Int;
	public static var SIZE_DOWNLOAD:Int;
	public static var SIZE_UPLOAD:Int;
	public static var SPEED_DOWNLOAD:Int;
	public static var SPEED_UPLOAD:Int;
	public static var SSL_VERIFYRESULT:Int;
	public static var STARTTRANSFER_TIME:Int;
	public static var TOTAL_TIME:Int;
	public static var HTTP_CONNECTCODE:Int;
	public static var HTTPAUTH_AVAIL:Int;
	public static var RESPONSE_CODE:Int;
	public static var PROXYAUTH_AVAIL:Int;
	public static var OS_ERRNO:Int;
	public static var NUM_CONNECTS:Int;
	public static var SSL_ENGINES:Int;
	public static var COOKIELIST:Int;
	public static var FTP_ENTRY_PATH:Int;
	public static var REDIRECT_URL:Int;
	public static var APPCONNECT_TIME:Int;
	public static var PRIMARY_IP:Int;
	public static var CERTINFO:Int;
	public static var CONDITION_UNMET:Int;
	public static var RTSP_CLIENT_CSEQ:Int;
	public static var RTSP_CSEQ_RECV:Int;
	public static var RTSP_SERVER_CSEQ:Int;
	public static var RTSP_SESSION_ID:Int;
	public static var LOCAL_IP:Int;
	public static var LOCAL_PORT:Int;
	public static var PRIMARY_PORT:Int;
	static function __init__(){
		CONNECT_TIME = untyped __cpp__ ("CURLINFO_CONNECT_TIME");
		CONTENT_LENGTH_DOWNLOAD = untyped __cpp__ ("CURLINFO_CONTENT_LENGTH_DOWNLOAD");
		CONTENT_LENGTH_UPLOAD = untyped __cpp__ ("CURLINFO_CONTENT_LENGTH_UPLOAD");
		CONTENT_TYPE = untyped __cpp__ ("CURLINFO_CONTENT_TYPE");
		EFFECTIVE_URL = untyped __cpp__ ("CURLINFO_EFFECTIVE_URL");
		FILETIME = untyped __cpp__ ("CURLINFO_FILETIME");
		HEADER_OUT = untyped __cpp__ ("CURLINFO_HEADER_OUT");
		HEADER_SIZE = untyped __cpp__ ("CURLINFO_HEADER_SIZE");
		HTTP_CODE = untyped __cpp__ ("CURLINFO_HTTP_CODE");
		LASTONE = untyped __cpp__ ("CURLINFO_LASTONE");
		NAMELOOKUP_TIME = untyped __cpp__ ("CURLINFO_NAMELOOKUP_TIME");
		PRETRANSFER_TIME = untyped __cpp__ ("CURLINFO_PRETRANSFER_TIME");
		PRIVATE = untyped __cpp__ ("CURLINFO_PRIVATE");
		REDIRECT_COUNT = untyped __cpp__ ("CURLINFO_REDIRECT_COUNT");
		REDIRECT_TIME = untyped __cpp__ ("CURLINFO_REDIRECT_TIME");
		REQUEST_SIZE = untyped __cpp__ ("CURLINFO_REQUEST_SIZE");
		SIZE_DOWNLOAD = untyped __cpp__ ("CURLINFO_SIZE_DOWNLOAD");
		SIZE_UPLOAD = untyped __cpp__ ("CURLINFO_SIZE_UPLOAD");
		SPEED_DOWNLOAD = untyped __cpp__ ("CURLINFO_SPEED_DOWNLOAD");
		SPEED_UPLOAD = untyped __cpp__ ("CURLINFO_SPEED_UPLOAD");
		SSL_VERIFYRESULT = untyped __cpp__ ("CURLINFO_SSL_VERIFYRESULT");
		STARTTRANSFER_TIME = untyped __cpp__ ("CURLINFO_STARTTRANSFER_TIME");
		TOTAL_TIME = untyped __cpp__ ("CURLINFO_TOTAL_TIME");
		HTTP_CONNECTCODE = untyped __cpp__ ("CURLINFO_HTTP_CONNECTCODE");
		HTTPAUTH_AVAIL = untyped __cpp__ ("CURLINFO_HTTPAUTH_AVAIL");
		RESPONSE_CODE = untyped __cpp__ ("CURLINFO_RESPONSE_CODE");
		PROXYAUTH_AVAIL = untyped __cpp__ ("CURLINFO_PROXYAUTH_AVAIL");
		OS_ERRNO = untyped __cpp__ ("CURLINFO_OS_ERRNO");
		NUM_CONNECTS = untyped __cpp__ ("CURLINFO_NUM_CONNECTS");
		SSL_ENGINES = untyped __cpp__ ("CURLINFO_SSL_ENGINES");
		COOKIELIST = untyped __cpp__ ("CURLINFO_COOKIELIST");
		FTP_ENTRY_PATH = untyped __cpp__ ("CURLINFO_FTP_ENTRY_PATH");
		REDIRECT_URL = untyped __cpp__ ("CURLINFO_REDIRECT_URL");
		APPCONNECT_TIME = untyped __cpp__ ("CURLINFO_APPCONNECT_TIME");
		PRIMARY_IP = untyped __cpp__ ("CURLINFO_PRIMARY_IP");
		CERTINFO = untyped __cpp__ ("CURLINFO_CERTINFO");
		CONDITION_UNMET = untyped __cpp__ ("CURLINFO_CONDITION_UNMET");
		RTSP_CLIENT_CSEQ = untyped __cpp__ ("CURLINFO_RTSP_CLIENT_CSEQ");
		RTSP_CSEQ_RECV = untyped __cpp__ ("CURLINFO_RTSP_CSEQ_RECV");
		RTSP_SERVER_CSEQ = untyped __cpp__ ("CURLINFO_RTSP_SERVER_CSEQ");
		RTSP_SESSION_ID = untyped __cpp__ ("CURLINFO_RTSP_SESSION_ID");
		LOCAL_IP = untyped __cpp__ ("CURLINFO_LOCAL_IP");
		LOCAL_PORT = untyped __cpp__ ("CURLINFO_LOCAL_PORT");
		PRIMARY_PORT = untyped __cpp__ ("CURLINFO_PRIMARY_PORT");
	}
}